//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseBooking
    {
        public int Id { get; set; }
        public int TrainingCourseTimetableId { get; set; }
        public int UserId { get; set; }
        public string Feedback { get; set; }
        public System.DateTime BookingTime { get; set; }
    
        public virtual TrainingCourseTimetable TrainingCourseTimetable { get; set; }
        public virtual User User { get; set; }
    }
}
