//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_Assignment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FIT5032_Assignment_ModelContainer : DbContext
    {
        public FIT5032_Assignment_ModelContainer()
            : base("name=FIT5032_Assignment_ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TrainingCourse> TrainingCourses { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Coach> Coaches { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<CoachRole> CoachRoles { get; set; }
        public virtual DbSet<TrainingCourseTimetable> TrainingCourseTimetables { get; set; }
        public virtual DbSet<TrainningCourseCoach> TrainningCourseCoaches { get; set; }
        public virtual DbSet<CourseBooking> CourseBookings { get; set; }
        public virtual DbSet<UserSkills> UserSkills { get; set; }
        public virtual DbSet<CourseWishList> CourseWishLists { get; set; }
        public virtual DbSet<SubScribe> SubScribes { get; set; }
    }
}
