//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingCourseTimetable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainingCourseTimetable()
        {
            this.TrainningCourseCoaches = new HashSet<TrainningCourseCoach>();
        }
    
        public int Id { get; set; }
        public System.DateTime CourseStartTime { get; set; }
        public System.DateTime CourseEndTime { get; set; }
        public int TrainingCourseId { get; set; }
        public bool IsLastOne { get; set; }
    
        public virtual TrainingCourse CourseId { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainningCourseCoach> TrainningCourseCoaches { get; set; }
    }
}
